website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated: 
        flash('Already logged in, please sign out first!', category='error')
        return redirect(url_for('views.home'))

    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        user = User.query.filter_by(Email=email).first()
        if user:
            if check_password_hash(user.UserPassword, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Email or Password incorrect!', category='error')
        else:
            flash('Email or Password incorrect!', category='error')

    return render_template("login.html", user=current_user)    

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        email = request.form['email']
        name = request.form['name']
        password = request.form['password']

        #Checking if the email is already in the database
        user = User.query.filter_by(Email=email).first()
        if user:
            flash('Account already exists.', category='error')

        elif len(name) < 2:
            flash('First name must be greater than 1 character.', category='error')

        elif len(password) < 7:
            flash('Password must be at least 7 characters.', category='error')

        else:
            new_user = User(UserName=name, Email=email, UserPassword=generate_password_hash(
                password, method='sha256'), Permission="Customer")

            db.session.add(new_user)
            db.session.commit()
            flash('Account created, please sign in!', category='success')

    return redirect(url_for('auth.login'))

website/views.py
from flask import Blueprint, redirect, render_template, request, session, url_for, flash
from . import db
from .models import *
from .graphs import *
from flask_login import current_user
from functools import wraps
from sqlalchemy import func
from werkzeug.security import generate_password_hash

views = Blueprint('views', __name__)

@views.route('/testing')
def testing():
    #Table
    if customer_table.query.count() != 4:
        testTable1 = customer_table(Seats = 4, Available = 1)
        testTable2 = customer_table(Seats = 2, Available = 2)
        testTable3 = customer_table(Seats = 5, Available = 3)
        testTable4 = customer_table(Seats = 6, Available = 1) 
        db.session.add(testTable1)
        db.session.add(testTable2)
        db.session.add(testTable3)
        db.session.add(testTable4)
        db.session.commit()


    #Food Items
    if FoodItem.query.count() != 6:
        test1 = FoodItem(FoodName = "Tacos",  UnitPrice = 8.99, ItemCategory = "Main Courses", GlutenFree = False, ContainsMeat = True, Vegan = False, Cals = 458)
        test2 = FoodItem(FoodName = "Quesadillas", UnitPrice = 6.99, ItemCategory = "Main Courses", GlutenFree = True, ContainsMeat = False, Vegan = False, Cals = 378)
        test3 = FoodItem(FoodName = "Fajita", UnitPrice = 6.99, ItemCategory = "Main Courses", GlutenFree = False, ContainsMeat = True, Vegan = False, Cals = 378)
        test4 = FoodItem(FoodName = "Burrito", UnitPrice = 6.99, ItemCategory = "Main Courses", GlutenFree = False, ContainsMeat = False, Vegan = True, Cals = 350)
        test5 = FoodItem(FoodName = "Pozole", UnitPrice = 6.99, ItemCategory = "Main Courses", GlutenFree = False, ContainsMeat = False, Vegan = False, Cals = 503)
        test6 = FoodItem(FoodName = "Menudo", UnitPrice = 6.99, ItemCategory = "Main Courses", GlutenFree = False, ContainsMeat = False, Vegan = False, Cals = 500)
        db.session.add(test1)
        db.session.add(test2)
        db.session.add(test3)
        db.session.add(test4)
        db.session.add(test5)
        db.session.add(test6)
        db.session.commit()


    if User.query.count() != 3:
        new_user1 = User(UserName="Alan Alan", Email="alanalan@gmail.com",
                         UserPassword=generate_password_hash("testing123", method='sha256'), Permission="Waiter")
        
        new_user2 = User(UserName="Bob Bob", Email="bobbob@gmail.com",
                         UserPassword=generate_password_hash("testing123", method='sha256'), Permission="Chef")
        
        new_user3 = User(UserName="Charlie Charlie", Email="charliecharlie@gmail.com",
                         UserPassword=generate_password_hash("testing123", method='sha256'), Permission="Owner")
        

        db.session.add(new_user1)
        db.session.add(new_user2)
        db.session.add(new_user3)
        db.session.commit()

    return("Done!")


@views.route('/base')
def base():
    return render_template("base.html", cart_products=cart_products(), notif_count=notif_count())


@views.route('/')
def home():
    x = db.session.query(Notification.typeNotification)
    return render_template("home.html", x=x, cart_products=cart_products(), notif_count=notif_count())


@views.route('/table')
def tables():
    ListAll =  customer_table.query.all()
    popups = {"add-table-popup": "+", "table-popup": "?"}
    return render_template("tables.html", res=ListAll, popups=popups, cart_products=cart_products(), notif_count=notif_count())


@views.route('/prod')
def product():
    ListAll = FoodItem.query.all()
    popups = {"add-dish-popup": "+", "allergy-popup": "?"}
    return render_template("Foodeditui.html", res= ListAll, popups=popups, cart_products=cart_products(), notif_count=notif_count())


@views.route('/menu')
def menu():
    ListAll = FoodItem.query.all()
    popups = {"add-dish-popup": "+", "allergy-popup": "?"}
    return render_template("menu.html", res= ListAll, popups=popups, cart_products=cart_products(), notif_count=notif_count())


@views.route('/payment')
def payment():
    cart = Cart.query.filter_by(Fk_UserID=current_user.UserID)
    cart_total = 0
    for item in cart:
        food_item = FoodItem.query.filter_by(FoodID=item.Fk_FoodID).first()
        cart_total += item.Quantity * food_item.UnitPrice

    cart_total = float(cart_total)
    vat = 0.2 * cart_total
    vat_string = f"£{vat:.2f}"
    cart_total += vat
    total_string = f"{cart_total:.2f}"
    total_pounds, total_pence = total_string.split(".")

    return render_template("payment.html", vat=vat_string, total_pounds=total_pounds, total_pence=total_pence, cart_products=cart_products(), notif_count=notif_count())


@views.route('/notif')
def notification():
    # OrderID, Total Price
    # Individual products: name, quantity, price
    ListAll = Notification.query.all()
    totalString = "N/A"
    totalPrice = 0
    products = {}

    for notif in ListAll:
        if notif.FK_OrderID != None:
            NotificationID = notif.NotificationID
            products[NotificationID] = []
            order = Orders.query.filter_by(OrderID=notif.FK_OrderID).first()
            totalPrice = order.UnitPrice
            order_items = OrderItem.query.filter_by(OrderID=notif.FK_OrderID)
            for item in order_items:
                food = FoodItem.query.filter_by(FoodID=item.FoodID).first()
                totalPrice += food.UnitPrice * item.Quantity
                products[notif.NotificationID].append(f"{item.Quantity}x {food.FoodName} (£{food.UnitPrice * item.Quantity:.2f})")
    
    totalString = f"£{totalPrice:.2f}"

    popups = {"order-popup": "?"}

    return render_template("notifcentre.html", res=ListAll, totalString=totalString, products=products, popups=popups, notif_count=notif_count())


@views.route('/staff')
def staff():
    return render_template("staff_management.html", notif_count=notif_count())


@views.route('/order_tracker/<int:order_id>')
def order(order_id):
    notif = Notification.query.filter_by(FK_OrderID=order_id).first()
    return render_template("order_tracker.html", order_id=order_id, status=notif.statusNotification)


@views.route('/order_tracker_staff/<int:order_id>')
def order_staff(order_id):
    notif = Notification.query.filter_by(FK_OrderID=order_id).first()
    totalString = "N/A"
    totalPrice = 0

    productList = []
    order = Orders.query.filter_by(OrderID=notif.FK_OrderID).first()
    totalPrice = order.UnitPrice
    order_items = OrderItem.query.filter_by(OrderID=notif.FK_OrderID)
    for item in order_items:
        food = FoodItem.query.filter_by(FoodID=item.FoodID).first()
        totalPrice += food.UnitPrice * item.Quantity
        productList.append(f"{item.Quantity}x {food.FoodName} (£{food.UnitPrice * item.Quantity:.2f})")

    totalString = f"£{totalPrice:.2f}"
    return render_template("order_tracker_staff.html", order_id=order_id, status=notif.statusNotification, totalString=totalString, productList=productList, notif_count=notif_count())


@views.route('/feedback')
def feedback():

    # Average Star Review
    avg_stars = "N / A"
    result = db.session.execute("SELECT AVG(starReview) FROM Reviews;")
    for row in result: # There's only one row
        if row[0] != None:
            avg_stars = f"{row[0]:.1f}"


    # List of Reviews
    reviews = db.session.execute("SELECT User.UserName, Reviews.starReview, Reviews.timeReview, Reviews.reviewID, Reviews.textReview " + 
        "FROM Reviews LEFT JOIN User ON Reviews.Fk_UserID = User.UserID " +
        "ORDER BY Reviews.timeReview DESC;")

    return render_template("feedback.html", avg_stars=avg_stars, dishes_graph=dishes_graph(), reviews=reviews, notif_count=notif_count())


## POST REQUESTS

#POST REQUEST FOR STORING REVIEW
@views.route('/review_store', methods=["POST"])
def review_store():
    stars = request.form.get("stars")
    review = request.form.get("review")
    review_row = Reviews(Fk_UserID=current_user.UserID, textReview=review, starReview=int(stars))
    db.session.add(review_row)
    db.session.commit()

    return "Success", 200


#POST REQUEST FOR ADDING A TABLE
@views.route("/add_table", methods=["POST"])
def add_table():
  seats = int(request.form.get("seats"))
  NewTable = customer_table(Seats = seats, Available = 1) 
  db.session.add(NewTable)
  db.session.commit()
  return "Success", 200


#POST REQUEST FOR DELETING PRODUCT FROM DB
@views.route('/delete_product', methods=["POST"])
def delete_product():
    food_id = int(request.form.get("id"))
    food = FoodItem.query.filter_by(FoodID=food_id).first()
    db.session.delete(food)
    db.session.commit()

    return "Success", 200

#POST REQUEST FOR CALLING WAITER
@views.route('/call_waiter', methods=["POST"])
def call_waiter():
    notif = Notification(statusNotification = 1, typeNotification = 2, FK_UserID = current_user.UserID)
    db.session.add(notif)
    db.session.commit()

    return "Success", 200

#POST REQUEST FOR DELETING NOTIFICATION FROM DB
@views.route('/delete_notif', methods=["POST"])
def delete_notif():
    NotifID = int(request.form.get("id"))
    notification = Notification.query.filter_by(NotificationID=NotifID).first()
    if notification:
        db.session.delete(notification)
        db.session.commit()

    return "Success", 200

#POST REQUEST FOR DELETING NOTIFICATION FROM DB
@views.route('/delete_review', methods=["POST"])
def delete_review():
    RevID = int(request.form.get("id"))
    rev = Reviews.query.filter_by(reviewID=RevID).first()
    if rev:
        db.session.delete(rev)
        db.session.commit()

    return "Success", 200

# Helper function to get the html for the products in cart
def cart_products():
    cart = Cart.query.filter_by(Fk_UserID=current_user.UserID)
    cart_items = {}
    cart_total = 0
    for item in cart:
        food_item = FoodItem.query.filter_by(FoodID=item.Fk_FoodID).first()
        cart_items[item.cartID] = f"{item.Quantity}x {food_item.FoodName} (£{item.Quantity * food_item.UnitPrice:.2f})"

website/templates/Foodeditui.html
{% extends "base.html" %}
  {% block head %}
    <meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/Foodeditui.css') }}">
    <title>
      Oaxaca - Allergies & Calories
    </title>
  {% endblock %}
  
  {% block content %}
    <div>
    <select name="option" id="show all" class="dropbar">
        <option value="show">Show All  </option>
        <option value="option 2">Select All</option>
        <option value="option 3">Select All</option>
        <option value="option 4">Select All</option>
      </select>
      <br>
      <br>
      <br>
      <br>
    </div>
  
    <table>
      <tbody><tr>
        <th>Name of product</th>
        <th>Cals</th> 
        <th><img src="{{ url_for('static', filename='images/Vector.svg') }}" alt="Contains meat"></th>
        <th><img src="{{ url_for('static', filename='images/mdi_gluten-free.svg') }}" alt="Gluten free"></th>
        <th><img src="{{ url_for('static', filename='images/iconoir_vegan.svg') }}" alt="Vegan"></th>
        <th>Price</th>
      </tr>
      {% for food in res %}
      <tr id="{{ food.FoodID }}">
        <td>{{ food.FoodName }}</td>
        <td>{{ food.Cals }}</td>
        <td>{% if food.GlutenFree==True %}
          <img src="{{ url_for('static', filename='images/Tick.svg') }}" alt="Gluten_Icon" />
          {% endif %}</td>
        <td>{% if food.ContainsMeat==True %}
          <img src="{{ url_for('static', filename='images/Tick.svg') }}" alt="Meat_icon">
          {% endif %}</td>
        <td>{% if food.Vegan==True %}
          <img src="{{ url_for('static', filename='images/Tick.svg') }}" alt="Vegan_Icon">
          {% endif %}</td>
        <td class="td-price">
          <span>
            {{ food.UnitPrice|round(2) }} £
          </span>
          <img class="delete-button" src="{{ url_for('static', filename='images/delete.png') }}" alt="delete-button">
        </td>     
      </tr>
      {% endfor %}
    </tbody></table>
    </div>

</div>

<script>
  let rows = Array.from(document.querySelectorAll("tr"));
  rows.forEach(function (tr) {
    let delete_button = tr.querySelector(".delete-button");
    if (delete_button) {
      tr.onmouseover = function() {
        delete_button.style.visibility = "visible";
      }
      tr.onmouseout = function() {
        delete_button.style.visibility = "hidden";
      }

      delete_button.onclick = function() {
        $.ajax({
          url: '/delete_product',
          type: 'POST',
          data: {id: tr.id},
          success: function(data) {
            $(".content").prepend('<div class="notification"><div class="notification-message"></div></div>');
            $(".notification-message").html("Product deleted!");
          },
          error: function(error) {
            console.log(error);
          }
        });
        tr.remove();
      }
    }
  });
</script>
  
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script> 
    {% block head %}
    {% endblock %}
</head>

<body>
    <div class="toplogo-container-parent">
        <img src="{{ url_for('static', filename='images/Logo.svg') }}" alt="toplogo">
    </div>

    <nav class="navbar">
        <ul class="navbar-nav">
            <li class="nav-item hamburger-icon" onclick="toggleSidebar()">
                <a href="#" class="nav-link">
                    <img src="{{ url_for('static', filename='images/sidebar/hamburger.svg') }}" alt="menubutton">
                </a>
            </li>

            <div class="navbar-top">
                <li class="nav-item user-profile">
                    <a href="#" class="nav-link">
                        <img src="{{ url_for('static', filename='images/sidebar/user-icon.svg') }}" alt="user">
                        <div class="summary-text">
                            <div>
                                {{ current_user.UserName }}
                            </div>
                            <div class="summary-text-small">
                                {{ current_user.Permission }}
                            </div>
                        </div>
                    </a>
                </li>
                {% if current_user.Permission != "Customer" %}
                    <div class="notif-bell">
                        <img src="{{ url_for('static', filename='images/sidebar/bell.svg') }}" alt="bell">
                        <div class="bell-text">{{ notif_count }}</div>
                    </div>
                {% endif %}
            </div>
            {% if current_user.Permission == "Customer" %}
                <li class="nav-item">
                    <a href="{{ url_for('views.menu') }}" class="nav-link">
                        <img src="{{ url_for('static', filename='images/sidebar/food-menu-icon.svg') }}" alt="menu">
                        <span class="link-text">Menu</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{{ url_for('views.product') }}" class="nav-link">
                        <img src="{{ url_for('static', filename='images/sidebar/allergies-icon.svg') }}"
                            alt="allergies and calories">
                        <span class="link-text">Allergies and calories</span>
                    </a>
                </li>

                <li class="nav-item waiterbutton">
                    <a href="#" class="nav-link">
                        <img src="{{ url_for('static', filename='images/sidebar/waiter-icon.svg') }}" alt="call a waiter">
                        <span class="link-text">Call a waiter</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{{ url_for('views.payment') }}" class="nav-link">
                        <img src="{{ url_for('static', filename='images/sidebar/payment-icon.svg') }}" alt="payment">
                        <span class="link-text">Payment</span>
                    </a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a href="{{ url_for('views.product') }}" class="nav-link">
                        <img src="{{ url_for('static', filename='images/sidebar/food-menu-icon.svg') }}" alt="menu">
                        <span class="link-text">Edit Menu</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('views.notification' )}}" class="nav-link">
                        <img src="{{ url_for('static', filename='images/sidebar/checklist-icon.svg') }}" alt="ordered food">
                        <span class="link-text">Ordered food</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('views.feedback') }}" class="nav-link">
                        <img src="{{ url_for('static', filename='images/sidebar/material-symbols_rate-review-outline.svg') }}" alt="review">
                        <span class="link-text">Statistics</span>
                    </a>
                </li>
            {% endif %}
            <li class="nav-item">
                <a href="{{ url_for('auth.logout') }}" class="nav-link">
                    <img src="{{ url_for('static', filename='images/sidebar/ic_baseline-log-out.svg') }}" alt="logout">
                    <span class="link-text">Log Out</span>
                </a>
            </li>
        </ul>
    </nav>

    <div class="content">
        <div class="helper-buttons">
            {% if cart_products %}
                <div class="circle-btn popup-btn" popup="basket-popup">
                    <img src="{{ url_for('static', filename='images/basket.svg') }}" alt="basket-icon">
                </div>
            {% endif %}

            {% if popups %}
                {% for popup, popup_type in popups.items() %}
                    <div class="circle-btn popup-btn" popup="{{ popup }}">{{ popup_type }}</div>
                {% endfor %}
            {% endif %}

        </div>

        {% block content %}
        
        {% endblock %}

        <div id="table-popup" class="helper-popup">
            <div class="helper-title">Table Status</div>
            <div class="helper-subtitle">The following dots show the status of the tables:</div>
            <div class="helper-content">
                <span><img src="{{ url_for('static', filename='images/green-light.svg') }}" alt="green-dot">Available</span>
                <span><img src="{{ url_for('static', filename='images/yellow-light.svg') }}" alt="yellow-dot">Reserved for the next two hours</span>
                <span><img src="{{ url_for('static', filename='images/red-light.svg') }}" alt="red-dot">Occupied</span>
            </div>
        </div>

        <div id="order-popup" class="helper-popup">
            <div class="helper-title">Order Status</div>
            <div class="helper-subtitle">The following dots show the status of the order:</div>
            <div class="helper-content">
                <span><img src="{{ url_for('static', filename='images/green-light.svg') }}" alt="green-dot">Served</span>
                <span><img src="{{ url_for('static', filename='images/yellow-light.svg') }}" alt="yellow-dot">In Progress</span>
                <span><img src="{{ url_for('static', filename='images/red-light.svg') }}" alt="red-dot">Waiting</span>
            </div>
        </div>

        <div id="allergy-popup" class="helper-popup">
            <div class="helper-title">Allergies Informations</div>
            <div class="helper-subtitle">The following symbols show the allergies of the dishes:</div>
            <div class="helper-content">
                <span><img src="{{ url_for('static', filename='images/menu/mdi_meat.svg') }}" alt="Meat Icon">Contains meat.</span>
                <span><img src="{{ url_for('static', filename='images/menu/mdi_gluten-free.svg') }}" alt="Gluten Free Icon">Gluten free.</span>
                <span><img src="{{ url_for('static', filename='images/menu/Group.svg') }}" alt="Vegan Icon">Vegan</span>
            </div>
        </div>

        <div id="add-table-popup" class="helper-popup">
            <div class="helper-title">Add a table</div>
            <div class="helper-subtitle">Choose the number of seats here:</div>
            <div class="helper-content">
                <input id="table_seats" type="text" placeholder="Number of seats", pattern="^[0-9]*$" />
                <div id="add-table-btn" class="white-button">Add table</div>
            </div>
        </div>

        <div id="add-dish-popup" class="helper-popup">
            <div class="helper-title">Add a Dish</div>
            <div class="helper-content">
                <form id="add-dish-form">
                    <div class="dish-main">
                        <div class="dish-textfields">
                            <input id="dish_name" name="dish_name" type="text" placeholder="Name"/>
                            <input id="dish_price" name="dish_price" type="text" placeholder="£Price (0-9 and .)" />
                        </div>
                        <div class="dish-checkboxes">
                            <label class="popup-checkbox">
                                <img src="{{ url_for('static', filename='images/menu/mdi_meat.svg') }}" alt="Meat Icon">
                                <span>Contains meat</span>
                                <input name="meat" id="meat" type="checkbox">
                            </label>
                            <label class="popup-checkbox">
                                <img src="{{ url_for('static', filename='images/menu/mdi_gluten-free.svg') }}" alt="Gluten Free Icon">
                                <span>Gluten free</span>
                                <input name="gluten" id="gluten" type="checkbox">
                            </label>
                            <label class="popup-checkbox">
                                <img src="{{ url_for('static', filename='images/menu/Group.svg') }}" alt="Vegan Icon">
                                <span>Vegan</span>
                                <input name="vegan" id="vegan" type="checkbox">
                            </label>
                        </div>
                    </div>
                </form>
                <div class="dish-btns">
                    <div id="add-dish-btn" class="white-button">Add dish</div>
                </div>
            </div>
        </div>

        <div id="add-worker-popup" class="helper-popup">
            <div class="helper-title">Add a worker</div>
            <div class="helper-content">
                <div class="worker-main">
                    <div class="worker-textfields">
                        <input id="worker_name" type="text" placeholder="Name"/>
                        <input id="worker_email" type="text" placeholder="Email" />
                        <input id="worker_password" type="password" placeholder="Password" />
                    </div>
                    <div class="worker-checkboxes">
                        <label class="popup-checkbox">
                            <span>Worker</span>
                            <input type="checkbox">
                        </label>
                        <label class="popup-checkbox">
                            <span>Chef</span>
                            <input type="checkbox">
                        </label>
                    </div>
                </div>
                <div class="worker-btns">
                    <div id="confirm-worker-btn" class="white-button">Confirm</div>
                </div>
            </div>
        </div>

        <div id="basket-popup" class="helper-popup">
            <div class="helper-title">Basket</div>
            <div class="helper-subtitle">View basket details below:</div>
            <div class="helper-content">
                {{ cart_products|safe }}
            </div>
        </div>
    </div>

    <script src="{{ url_for('static', filename='js/base.js') }}"></script>
    {% block scripts %}
    {% endblock %}
</body>

</html>

website/templates/gluten_menu.html
{% for food in res %}
    {% if food.GlutenFree==True %}
    <div id="{{ food.FoodID }}" class="food_container">
        <div class="icon">
            <img src="{{ url_for('static', filename='images/menu/mdi_gluten-free.svg') }}" alt="Gluten_Icon" />
        </div>

        <div class="food_info">
            <div class="food_name">{{ food.FoodName }}</div>
            <div class="food_price">{{'%0.2f' % food.UnitPrice|float}}£</div>
        </div>
    </div>
    {% endif %}
{% endfor %}

website/templates/home.html
{% extends "base.html" %}
{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
  <title>
    Oaxaca - Home
  </title>
{% endblock %}

{% block content %}
  <div class="home-content">
    <div class="mainlogo-container-parent">
      <img src="{{ url_for('static', filename='images/Logo.svg') }}" alt="logo">
    </div>
    
    <div class="belowlogo-container-parent">
      <img src="{{ url_for('static', filename='images/home/belowLogo.svg') }}" alt="belowlogo">
    </div>
    
    <div class="action">
      <button class="menubutton" type="submit">View Menu</button>
      <button class="waiterbutton" type="submit">Call a waiter</button>
    </div>
  </div>
{% endblock %}


{% block scripts %}
<script src="{{ url_for('static', filename='js/home.js') }}"></script>
{% endblock %}

website/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
  <title>Oaxaca - Login</title>
</head>

<div class="logo-container">
  <a href="{{ url_for('views.home') }}">
  <img src="{{ url_for('static', filename='images/Logo.svg') }}" alt="logo">
  </a>
</div>

<br>

<body>
  <div class="login-content">
      <img id="peopleImage" src="{{ url_for('static', filename='images/Vector Log.svg') }}" alt="People at a table"
      width="392" height="480">
    <div class="login-form">
      <h1>Log In</h1>
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              <div id="flashedMessages">
                {% for category, message in messages %}
                  <div class="flashMessage {{ category }}">
                    {{ message }}
                  </div>
                {% endfor %}
              </div>
          {% endif %}
        {% endwith %}
      <form action="{{ url_for('auth.login') }}" method="post">
        <div class="login-inner-content">
          <div id="nameField" class="input-field">
            <img src="https://img.icons8.com/ios-glyphs/512/user--v1.png" width="20" height="20" alt="Person Icon">
            <input id="name" name="name" type="text" placeholder="Your Name" autocomplete="given-name">
          </div>

          <div id="emailField" class="input-field">
            <img src="https://img.icons8.com/ios-glyphs/512/secured-letter.png" width="20" height="20"
              alt="Letter Icon">
            <input id="email" name="email" type="text" placeholder="Your Email" autocomplete="nope">
          </div>

          <div id="passwordField" class="input-field">
            <img src="https://img.icons8.com/ios-glyphs/512/keyhole-shield.png" width="20" height="20"
              alt="Padlock Icon">
            <input id="password" name="password" type="password" placeholder="Your Password" autocomplete="nope">
            <img id="eyeIcon" src="{{ url_for('static', filename='images/show.svg') }}" alt="Eye Icon"
              onclick="togglePassword()">
          </div>

        </div>

        <div class="action">
          <button type="submit" formaction="{{ url_for('auth.signup') }}">Register</button>
          <button id="login-btn" type="submit" formaction="{{ url_for('auth.login') }}">Sign In</button>
        </div>
      </form>
    </div>
  </div>

  <script src="{{ url_for('static', filename='js/login.js') }}"></script>
</body>

</html>

website/templates/logout.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Profile Page</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
  <body>
    <section class="hero is-success is-fullheight">
      <div class="hero-body">
        <div class="container">
          <h1 class="title">
            {{g.user.username}}'s Profile
          </h1>
          <h2 class="subtitle">
            You are user number #{{g.user.id}}
          </h2>
        </div>
      </div>
    </section>
  </body>
</html>